name: Sync labels across org

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          gh auth setup-git
          gh auth status

      - name: Get repos and apply labels
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          ORG="your-org-name"
          LABEL_CONFIG=".github/labels.yml"

          # You can enhance this to read labels from the config if needed
          gh repo list $ORG --limit 1000 --json name -q '.[].name' | while read repo; do
            echo "Syncing labels for $ORG/$repo"
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              /repos/$ORG/$repo/labels \
              -f name="bug" \
              -f color="f29513" \
              -f description="Something isn't working" || true
          done
