name: Sync labels across org

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        uses: cli/cli-action@v2
        with:
          version: latest

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.PERSONAL_TOKEN }}"

      - name: Get repos and apply labels
        run: |
          ORG="your-org-name"
          LABEL_CONFIG=".github/labels.yml"

          gh repo list $ORG --limit 1000 --json name -q '.[].name' | while read repo; do
            echo "Syncing labels for $ORG/$repo"
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              /repos/$ORG/$repo/labels \
              -F name='bug' -F color='f29513' -F description='Something isn\'t working' || true
              # Repeat for all labels or use a more advanced script that reads from labels.yml
          done
